services:
  bancho.py:
    build: bancho.py
    restart: always
    volumes:
      - project:/osu-server
      - vscode-server:/root/.vscode-server
    environment:
      PROD_MODE: $PROD_MODE_BACKEND
      OSU_API_KEY: $OSU_API_KEY

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data
      - redis-etc:/etc

  mysql:
    build: mysql
    restart: always
    volumes:
      - project:/osu-server
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - "bancho.py:banchopy"

volumes:
  mysql-data:
  redis-data:
  redis-etc: # maybe bancho.py was born with the complexity when using docker. lol

  vscode-server:
  project:


networks:
  network:
