services:
  app:
    build:
      context: app
      target: builder
    restart: always
    ports:
      - 8080:8080
      - 10000:10000
    volumes:
      # - unix-sockets:/socket
      - project:/osu-server
    networks:
      - network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - network
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis-data:/data

  mysql:
    build:
      context: mysql
      target: builder
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - network

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
    volumes:
        - unix-sockets:/socket
    networks:
      - network

volumes:
  mysql-data:
  redis-data:
  # maybe bancho.py was born with the complexity when using docker. lol
  unix-sockets:
  project:
  python-data:

networks:
  network:
