services:
  bancho.py:
    build:
      context: app
      target: bancho.py
    restart: always
    ports:
      - 8081:8080
    volumes:
      - unix-sockets:/socket
      - project:/osu-server
    networks:
      - network
    environment:
      IS_DEV: $IS_DEV
      RUN_CODE_SERVER: $RUN_CODE_SERVER

  guweb:
    build:
      context: app
      target: guweb
    restart: always
    ports:
      - 8080:8080
      - 10000:10000
    volumes:
      - project:/osu-server
    networks:
      - network
    environment:
      IS_DEV: $IS_DEV
      RUN_CODE_SERVER: $RUN_CODE_SERVER

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - network
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis-data:/data
      - redis-etc:/etc

  mysql:
    build:
      context: mysql
      target: builder
    restart: always
    volumes:
        - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - network

  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80
    volumes:
        - unix-sockets:/socket
    networks:
      - network

volumes:
  mysql-data:
  redis-data:
  redis-etc:
  # maybe bancho.py was born with the complexity when using docker. lol
  unix-sockets:
  project:

networks:
  network:
